In [38]:
import os
import numpy as np #For array operations
import matplotlib.pyplot as plt
import os
import pickle
import sys
import keras
import time
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.layers.normalization import BatchNormalization
from keras.callbacks import TensorBoard 
from sklearn.model_selection import train_test_split

In [42]:
np.random.seed(42)
pickle_in = open("X.pickle", "rb")
X = pickle.load(pickle_in)
pickle_in.close()

pickle_in = open("y.pickle", "rb")
y = pickle.load(pickle_in)
pickle_in.close() 

print(X)
print(y)
dimX = len(X[0])
dimy = y.shape[1]

[[1.03355015e-03 1.82983208e-06 4.82740504e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [3.27593484e-05 8.93436775e-06 5.54609812e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [6.28702073e-05 1.71464202e-05 2.00041569e-05 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [2.51606193e-04 7.18874836e-05 3.71418665e-04 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [5.21664130e-07 3.91248097e-08 3.53553391e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [1.11358522e-03 1.97152886e-06 4.65835468e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [85]:
p = {'lr': [0.5, 5],
     'first_neuron':[32, 64, 128, 256],
     'hidden_layers':[0, 1, 2, 3],
     'shapes': [0.0, 0.2],
     'batch_size': [10, 20],
     'dropout': [0, 0.1],
     'epochs': [5, 15],
     'losses': ['categorical_crossentropy'],
     'activation':['relu', 'tanh'],
     'optimizer': ['adam', 'nadam'],
     'last_activation': ['softmax']}

In [86]:
def def_model(X, y, X_val, y_val, params):
    dimX = len(X[0])
    dimy = y.shape[1]

    model = Sequential()
    model.add(Dense(params['first_neuron'], activation=params['activation'], input_shape=(dimX,)))
    model.add(Dropout(params['dropout']))
    
    talos.utils.hidden_layers(model, params, 1)
    
    model.add(Dense(128, activation='relu'))
    model.add(Dense(dimy, activation=params['last_activation']))

    #Configure Model
    model.compile(loss=params['losses'], 
                  optimizer=params['optimizer'](lr_normalizer(params['lr'], params['optimizer'])),
                  metrics=['accuracy'])
    
    out = model.fit(X, y,
                    validation_data=[X_val, y_val],
                    batch_size=params['batch_size'],
                    epochs=params['epochs'],
                    verbose=2)
    return out, model

In [83]:
import talos

In [87]:
t = talos.Scan(x=X, y=y, x_val=X_val, y_val=y_val, params=p, model=def_model, experiment_name='talospepe')












  0%|                                                                                         | 0/2048 [00:00<?, ?it/s]

NameError: name 'lr_normalizer' is not defined

In [25]:
p = {
    'first_neuron': [12, 24, 48],
    'activation': ['relu', 'elu'],
    'batch_size': [10, 20, 30]
}

In [20]:
print(X[0])
print(y[0])

[1.03355015e-03 1.82983208e-06 4.82740504e-01 2.43977610e-06
 2.13480409e-06 3.45228318e-04 4.82160752e-04 2.01586500e-04
 0.00000000e+00 4.31535398e-05 6.79453318e-05 3.57732171e-04
 0.00000000e+00 6.88801075e-05 1.31168037e-04 5.22704244e-04
 2.88999766e-06 3.44814646e-02 7.50146707e-02 2.90731040e-01
 6.09944026e-07 4.82740504e-01 6.89629291e-02 1.18882983e-01
 3.37440858e-01 6.09944026e-07 4.54181095e-01 7.56968492e-02
 1.05577847e-01 2.90731040e-01 2.86515107e-02 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 5.24551862e-05
 4.63557459e-05 1.54133209e-06 1.34866558e-06 0.00000000e+00
 3.57732171e-04 5.17118169e-05 9.69087601e-05 3.07939988e-02
 0.00000000e+00 0.00000000e+00 0.00000000e+00 3.04972013e-07
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 5.51592714e-05 4.31535398e-05 6.88801075e-05
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 2.43977610e-06 3.45228318e-04
 2.13480409e-06 4.821607

In [80]:
 X, X_val, y, y_val = train_test_split(X, y, test_size=0.1, random_state=1)

In [75]:
print(len(X))
print(y.shape)

215101
(215101, 3)


In [76]:
print(len(X_val))
print(y_val.shape)

23901
(23901, 3)
